### ISSUE TITLE
Interference with freqtrade docker on port 8080

### ISSUE THREAD

**Issue by skeltavik** [mikekonan/freqtrade-proxy#1]
Hi,

Thanks for your proxy and the continuing development. I encountered some errors when running the proxy with it's default config on port 8080, which the frequi/API of freqtrade is also running on.

```
Error starting userland proxy: listen tcp4 0.0.0.0:8080: bind: address already in use.
```

Maybe having another port to run the proxy, would prevent this issue by default? For example port 8090?

Thanks in advance!

**Comment by mikekonan** [comment]
Are you using docker or local? 
I've just added an option to set a port over CLI

**Comment by skeltavik** [comment]
I'm using Docker for freqtrade itself.

Nice, thanks for the quick addition!

**Comment by mikekonan** [comment]
So, if you are starting proxy as a docker container you can change the bindable port as you want:
docker run --restart=always -p {anyport}:8080 --name freqtrade-proxy -d freqtrade-proxy
