### ISSUE TITLE
Getting below error 

### ISSUE THREAD

**Issue by PeetCrypto** [mikekonan/freqtrade-proxy#12]
Attaching to freqtrade-proxy
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy exited with code 1
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error
freqtrade-proxy    | standard_init_linux.go:228: exec user process caused: exec format error

Error is on Oracle Op ARM based proccessor.

**Comment by mikekonan** [comment]
what is the output of lscpu and uname -a?

**Comment by PeetCrypto** [comment]
fix used main-amd64 instead of main-arm64 in docker-compose.yml
