### ISSUE TITLE
Docker container repeatedly crashing and not restarting

### ISSUE THREAD

**Issue by bruzska** [mikekonan/freqtrade-proxy#13]
Hey after using your awesome project for a little while without issue, the proxy is now repeatedly crashing and not restarting regardless of the docker restart policy. The only error I've been able to find is:

FATA[0185] Error: %sread tcp 172.18.0.2:52570->99.84.133.34:443: read: connection reset by peer  caller="/src/proxy/kucoin/kucoin.go:135 (*ws).serveFor" stack="/src/proxy/kucoin/kucoin.go:135            (*ws).serveFor\n/usr/local/go/src/runtime/asm_amd64.s:1581 goexit"

Let me know if there's any other info I can provide to help get to the bottom of this.

**Comment by mikekonan** [comment]
Could you show your docker-compose.yml?

**Comment by bruzska** [comment]
> Could you show your docker-compose.yml?

    freqtrade-proxy:
        image: mikekonan/freqtrade-proxy:main
        restart: on-failure
        container_name: freqtrade-proxy   

The proxy is crashing after only a few minutes at the moment so I'm worried the issue may be bigger than simply a container not restarting.

**Comment by mikekonan** [comment]
about the restart policy - https://docs.docker.com/compose/compose-file/compose-file-v3/#restart_policy.

this error is about connection has been lost. How are you running the proxy?

**Comment by bruzska** [comment]
> about the restart policy - https://docs.docker.com/compose/compose-file/compose-file-v3/#restart_policy.
> 
> this error is about connection has been lost. How are you running the proxy?

I'm the following the Docker-compose (best way) method but I see that you've had a 60,000 timeout since I first setup the proxy. I'll try with this updated config and see if it makes a difference.
