### ISSUE TITLE
Limits

### ISSUE THREAD

**Issue by aumcara** [mikekonan/freqtrade-proxy#18]
Hi Mike,

Thanks for your work regarding this proxy tool for FreqTrade ... it seriously help.

I have actually a couple of bots using it and it works just fine.

Do you know the limits as far as the maximum number of bots able to connect to the proxy with Kucoin subaccounts ?

Thank you for your reply and pretty week-end to you.

**Comment by mikekonan** [comment]
I believe it can carry dozens of bots at the same time in case if your configuration allows that. 

There are known proxy paths that are not proxied for now, which could lead to 429 if all your bots will use these endpoints at the same time. So, if the community will support me to implement this, I will consider it more.

**Comment by aumcara** [comment]
Thank you mike for your reply.

**Comment by SmartManoj** [comment]
> There are known proxy paths that are not proxied for now
Is this?
https://github.com/mikekonan/exchange-proxy/blob/3f96b22542fd9dcb8656f4d1717f7e6e34d015be/proxy/kucoin/http.go#L18-L23

**Comment by mikekonan** [comment]
These ones are proxied over cache. Other paths proxied transparently.
