### ISSUE TITLE
verbosity for less spam in console

### ISSUE THREAD

**Issue by hippocritical** [mikekonan/freqtrade-proxy#21]
Hi, would it be possible to have message verbosity?
error, warning, info

would like to have less clutter in the tmux instance.

that great job! <3

**Comment by mikekonan** [comment]
[v1.0.12](https://github.com/mikekonan/freqtrade-proxy/releases/tag/v1.0.12)

use `-verbosity 0` or just ignore the parameter

**Comment by hippocritical** [comment]
ah thx!
