### ISSUE TITLE
Latest version is crashing

### ISSUE THREAD

**Issue by nuaimat** [mikekonan/freqtrade-proxy#23]
Hi 
with the latest version of mikekonan/freqtrade-proxy:main-amd64 (must be 1.0.12) 
i just did docker pull mikekonan/freqtrade-proxy:main-amd64
then started my docker-compose stack which was working fine on the previous version of mikekonan/freqtrade-proxy:main-amd64  

i am getting this error:

`time="2021-12-06T08:19:58Z" level=info msg="starting proxy server on :8080 port..." caller="/src/proxy/kucoin/kucoin.go:323 (*kucoin).Start"
time="2021-12-06T08:20:02Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:20:02Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:20:07Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:20:07Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:20:11Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:20:11Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:20:15Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:20:15Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:20:20Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:20:20Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:20:26Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:20:26Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:20:33Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:20:33Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:20:44Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:20:44Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:21:01Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:21:01Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:21:30Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:21:30Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:22:26Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:22:26Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:23:30Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:23:30Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:24:34Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:24:34Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:25:38Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:25:38Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:25:40Z" level=info msg="starting proxy server on :8080 port..." caller="/src/proxy/kucoin/kucoin.go:323 (*kucoin).Start"
time="2021-12-06T08:25:44Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:25:44Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:25:48Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:25:48Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:25:52Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:25:52Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:25:57Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:25:57Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:26:01Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:26:01Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:26:07Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:26:07Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:26:14Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:26:14Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581                                                        goexit"
time="2021-12-06T08:26:25Z" level=debug msg="proxying over - /kucoin/api/v1/currencies" caller="/src/proxy/kucoin/kucoin.go:303 (*kucoin).Start.func2"
time="2021-12-06T08:26:25Z" level=error msg="lookup openapi-v2.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:312 (*kucoin).Start.func2" stack="/src/proxy/kucoin/kucoin.go:312                                                                   (*kucoin).Start.func2\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1581`

**Comment by nuaimat** [comment]
ping openapi-v2.kucoin.com
PING openapi-v2.kucoin.com.cdn.cloudflare.net (104.18.19.110) 56(84) bytes of data.
64 bytes from 104.18.19.110 (104.18.19.110): icmp_seq=1 ttl=57 time=1.04 ms
64 bytes from 104.18.19.110 (104.18.19.110): icmp_seq=2 ttl=57 time=1.09 ms
64 bytes from 104.18.19.110 (104.18.19.110): icmp_seq=3 ttl=57 time=1.13 ms
^C
--- openapi-v2.kucoin.com.cdn.cloudflare.net ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 1.035/1.087/1.132/0.039 ms

**Comment by nuaimat** [comment]
reverting back to this image:
mikekonan/freqtrade-proxy:1.0.11-amd64
fixes the error.

**Comment by nuaimat** [comment]
Also, thank you so much for this amazing project, it came at the right time to save us from the 429 errors from kucoin, you're a life saver

**Comment by mikekonan** [comment]
very interesting - "lookup openapi-v2.kucoin.com: device or resource busy"

**Comment by mikekonan** [comment]
looks like DNS issue

**Comment by mikekonan** [comment]
what is your host os?

**Comment by slipx06** [comment]
Latest version is also crashing for me

```
freqtrade-proxy    | time="2021-12-06T13:18:15Z" level=debug msg="processing request - /kucoin/api/v1/market/candles?symbol=HTR-USDT&type=5min&startAt=1638646692&endAt=1638796692" caller="/src/proxy/kucoin/kucoin.go:253 (*kucoin).Start.func1"
freqtrade-proxy    | time="2021-12-06T13:18:15Z" level=debug msg="processing request - /kucoin/api/v1/market/candles?symbol=QRDO-USDT&type=15min&startAt=1638346692&endAt=1638796692" caller="/src/proxy/kucoin/kucoin.go:253 (*kucoin).Start.func1"
freqtrade-proxy    | time="2021-12-06T13:18:15Z" level=debug msg="processing request - /kucoin/api/v1/market/candles?symbol=THETA-USDT&type=15min&startAt=1638346692&endAt=1638796692" caller="/src/proxy/kucoin/kucoin.go:253 (*kucoin).Start.func1"
freqtrade-proxy    | time="2021-12-06T13:18:15Z" level=debug msg="processing request - /kucoin/api/v1/market/candles?symbol=ROSE-USDT&type=5min&startAt=1638646692&endAt=1638796692" caller="/src/proxy/kucoin/kucoin.go:253 (*kucoin).Start.func1"
freqtrade-proxy    | time="2021-12-06T13:18:15Z" level=debug msg="processing request - /kucoin/api/v1/market/candles?symbol=1INCH-USDT&type=5min&startAt=1638646692&endAt=1638796692" caller="/src/proxy/kucoin/kucoin.go:253 (*kucoin).Start.func1"
freqtrade-proxy    | time="2021-12-06T13:18:15Z" level=fatal msg="Get \"https://api.kucoin.com/api/v1/market/candles?endAt=1638796691&startAt=1638346500&symbol=BTT-USDT&type=15min\": dial tcp: lookup api.kucoin.com: device or resource busy" caller="/src/proxy/kucoin/kucoin.go:271 (*kucoin).Start.func1" stack="/src/proxy/kucoin/kucoin.go:271                                                                   (*kucoin).Start.func1\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\n/go/pkg/mod/github.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_arm64.s:1133                                                        goexit"
```

**Comment by mikekonan** [comment]
Are you using docker or local installation?

**Comment by slipx06** [comment]
> Are you using docker or local installation?

docker local build

**Comment by mikekonan** [comment]
@nuaimat try docker pull mikekonan/freqtrade-proxy:main-amd64

**Comment by nuaimat** [comment]
@mikekonan yes, the latest version on  mikekonan/freqtrade-proxy:main-amd64 works as expected. 

side note, I saw the error earlier and tried 
`ping openapi-v2.kucoin.com`
on the host OS (not inside docker) and it returned a response. so i don't think it was caused by a networking issue on the host but probably something inside the docker container.

**Comment by nuaimat** [comment]
working fine now, thanks
