### ISSUE TITLE
check this please

### ISSUE THREAD

**Issue by bibinvargheset** [mikekonan/freqtrade-proxy#3]
- freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair LTO/USDT due to ExchangeNotAvailable. Message: kucoin GET http://freqtrade-proxy:8080/kucoin/api/v1/market/candles?symbol=LTO-USDT&type=5min&startAt=1636827968&endAt=1636977968 500 Internal Server Error [HTTP]Failure: status code is NOT 200, GET /api/v1/market/candles?endAt=1636977968&startAt=1636827900&symbol=LTO-USDT&type=5min with body=, respond code=429 body={"code":"429000","msg":"Too Many Requests"}"

**Comment by mikekonan** [comment]
Looks like you producing requests, not over a proxy that leads to 429.

**Comment by bibinvargheset** [comment]
it happens only @ start, what should i change to fix it?

**Comment by bibinvargheset** [comment]
you have done gr8 job on this, dont feel bad we are bugging you again. you have solved a biggest issue with kucoin, binance proxy already availble if it can be intergrated would be great

Since multiple bot use simillar candles for simillar bots @start so if you can buffer those requests and provide that date to subsequest bot requests it would be good.

**Comment by mikekonan** [comment]
Won't plan to integrate binance since it is not working in my country. 
If someone wants to contribute that, I will help with the code architecture

**Comment by bibinvargheset** [comment]
it is already implemented in https://github.com/abanchev/binance-proxy so you can check that and intergrate that if possible,
