### ISSUE TITLE
Not working apparently on computers with ARM Cpu

### ISSUE THREAD

**Issue by aumcara** [mikekonan/freqtrade-proxy#6]
I did try to install your proxy on my Freqtrade bot.

Unfortunately it's apparently not compatible with ARM CPU based computer :-(

Is there a possibility to have your proxy working on such machine?

Thanks

**Comment by mikekonan** [comment]
https://github.com/mikekonan/freqtrade-proxy/releases/tag/v1.0.9 for binary or https://hub.docker.com/repository/registry-1.docker.io/mikekonan/freqtrade-proxy/tags?page=1&ordering=last_updated&name=arm
