### ISSUE TITLE
FATA[0266] 

### ISSUE THREAD

**Issue by jdk-sal3** [mikekonan/freqtrade-proxy#7]
FATA[0266] Wait ack message timeout in 10s               caller="github.com/mikekonan/freqtradeProxy/proxy/kucoin/kucoin.go:37 (*subscriptionManager).Subscribe" stack="github.com/mikekonan/freqtradeProxy/proxy/kucoin/kucoin.go:37                         (*subscriptionManager).Subscribe\ngithub.com/mikekonan/freqtradeProxy/proxy/kucoin/kucoin.go:253                        (*kucoin).Start.func1\ngithub.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/context.go:67 (*Context).Next\ngithub.com/qiangxue/fasthttp-routing@v0.0.0-20160225050629-6ccdc2a18d87/router.go:75  (*Router).HandleRequest\ngithub.com/valyala/fasthttp@v1.29.0/server.go:2251                                    (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.29.0/workerpool.go:223                                 (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.29.0/workerpool.go:195                                 (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581                                                              goexit"

**Comment by mikekonan** [comment]
That is expected behaviour for now, let docker restart the proxy
